name: Publish Docker Image

on:
  push:
    tags:
      - 'v*' 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/da-silva-romero-pdes-front:latest
            ${{ secrets.DOCKER_USERNAME }}/da-silva-romero-pdes-front:${{ github.ref_name }}

      - name: Inspect built image
        run: |
          docker images ${{ secrets.DOCKER_USERNAME }}/da-silva-romero-pdes-front:latest

      - name: Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/da-silva-romero-pdes-front:latest
            ${{ secrets.DOCKER_USERNAME }}/da-silva-romero-pdes-front:${{ github.ref_name }}
